var slider_entry = [
["/2019/02/tuyet-ung-linh-chu.html","https://i.imgur.com/VSdNNwX.jpg"],
["/2019/03/thieu-nien-ca-hanh.html","https://i.imgur.com/cp68JkB.jpg"],
["/2019/02/manh-the-thuc-than.html","https://i.imgur.com/HcNq453.jpg"],
["/2019/02/du-hoac-mieu-yeu.html","https://i.imgur.com/OXq7DcL.jpg"],
["/2019/02/dau-pha-thuong-khung.html","https://i.imgur.com/GYj3uMF.jpg"],
["/2019/02/ma-dao-to-su.html","https://i.imgur.com/GfGDTxT.jpg"],
];
'use strict';var slider_width=100;var sliderz_time=6000;var entry="",pick="",slider_entry_len=slider_entry.length;for(var i=0;i<slider_entry_len;i++){entry+='<div class="sliderz-entry" style="width:'+100/slider_entry_len+'%"><a class="sliderz-preview" href="'+slider_entry[i][0]+'"><img onload="lzld(this)" class="sliderz-preview-img" data-src="'+slider_entry[i][1].replace(slider_entry[i][1].split("/")[7], "s300")+'" src="//i.imgur.com/YdwUuUq.jpg"/></a></div>';pick='<span class="sliderz-number" data-slide-number='+i+' onclick="sliderz_goto(event)"></span>'+pick}var slider_entry_wrapper=jQuery('.sliderz-entry-list-wrapper')[0];slider_entry_wrapper.style.width=slider_entry_len*slider_width+'%';jQuery('.sliderz-entry-list').eq(0).html(entry);jQuery('.sliderz-pick').eq(0).html(pick);var slider_wrapper=jQuery('.sliderz-wrapper')[0];var sliderz_timer=setInterval(function(){sliderz_goto(-2)},sliderz_time);slider_wrapper.addEventListener("mouseenter",function(){clearInterval(sliderz_timer)});slider_wrapper.addEventListener("mouseleave",function(){sliderz_timer=setInterval(function(){sliderz_goto(-2)},sliderz_time)});var sliderz_goto=(function(){var slider_ctrl=jQuery('.sliderz-entry-list-wrapper')[0];var curpos=0,range=slider_entry_len,slider_wid=slider_width;var pickls=jQuery('.sliderz-number');return function(pos){if(pos==event)curpos=pos.target.dataset.slideNumber;else if(pos==-1){curpos=--curpos%range;curpos=curpos<0?range-1:curpos}else if(pos==-2)curpos=++curpos%range;slider_ctrl.style.left=-curpos*slider_wid+"%";for(var i=pickls.length-1;i>=0;i--)pickls[i].classList.remove("open");pickls[curpos].classList.add("open")}})();slider_entry="";entry="";slider_entry_wrapper="";slider_wrapper="";pick="";slider_width=0;slider_entry_len=0;
